"""
格式转换 — 将 Markdown 转为 txt / html
html 模式使用 md2html 模板，提供暗色模式、TOC 侧栏、代码复制等交互功能
Markdown → HTML 转换由 mistune 负责
"""
import re
from pathlib import Path
from datetime import date as date_type

import mistune


_TEMPLATE_PATH = Path(__file__).parent / "template.html"


def _kebab_id(text):
    """从标题文本提取 ASCII 单词生成 kebab-case id，纯中文则返回 None"""
    words = re.findall(r"[a-zA-Z0-9]+", text)
    if words:
        return "-".join(w.lower() for w in words)
    return None


def _count_reading_minutes(text):
    """估算阅读时间（分钟），按 250 字符/分钟"""
    chars = len(re.sub(r"\s", "", text))
    return max(1, round(chars / 250))


def _extract_subtitle(md_text):
    """提取 h1 之后第一个非空段落作为副标题，最长 200 字符"""
    heading_seen = False
    lines = []
    for line in md_text.split("\n"):
        stripped = line.strip()
        if not heading_seen:
            if re.match(r"^#\s+", stripped):
                heading_seen = True
            continue
        if not stripped or re.match(r"^#{1,6}\s", stripped):
            if lines:
                break
            continue
        lines.append(stripped)
        if len(" ".join(lines)) > 200:
            break
    subtitle = " ".join(lines).strip()
    return subtitle[:200] if subtitle else ""


# ---- mistune 自定义 renderer ----

class _TOCRenderer(mistune.HTMLRenderer):
    """给 h2/h3 注入 id 用于 TOC 导航，h1 隐藏（模板 doc-title 已有）"""

    def __init__(self, toc_map: dict):
        super().__init__()
        self._toc_map = toc_map

    def heading(self, text: str, level: int, **attrs):
        if level == 1:
            return ""
        plain = re.sub(r"<[^>]+>", "", text)
        kid = self._toc_map.get(plain)
        if kid and level in (2, 3):
            attrs["id"] = kid
        return super().heading(text, level, **attrs)


def _build_toc_and_body(md_text):
    """解析 markdown，返回 (toc_html, body_html)

    第一遍：正则扫描提取 h2/h3 标题信息，构建 TOC 和 id 映射
    第二遍：mistune 负责完整的 MD → HTML 转换
    """
    toc_entries = []  # [(id, text, level_class), ...]
    toc_map = {}       # {plain_text: id}
    heading_counter = 0

    for line in md_text.split("\n"):
        m = re.match(r"^(#{2,3})\s+(.+)$", line)
        if m:
            level = len(m.group(1))
            text = m.group(2).strip()
            heading_counter += 1
            kid = _kebab_id(text) or f"section-{heading_counter}"
            lvl_class = "lvl-2" if level == 2 else "lvl-3"
            toc_entries.append((kid, text, lvl_class))
            toc_map[text] = kid

    body_html = mistune.markdown(md_text, renderer=_TOCRenderer(toc_map))

    toc_html = "\n".join(
        f'<a href="#{kid}" class="{lvl}">{text}</a>'
        for kid, text, lvl in toc_entries
    )

    return toc_html, body_html


# ---- 公开 API ----


def md_to_txt(text):
    """Markdown → 纯文本"""
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    text = re.sub(r"\*{1,3}(.+?)\*{1,3}", r"\1", text)
    text = re.sub(r"!\[.*?\]\(.+?\)", "", text)
    text = re.sub(r"\[(.+?)\]\(.+?\)", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    text = re.sub(r"^[-*_]{3,}$", "", text, flags=re.MULTILINE)
    text = re.sub(r"^>\s?", "", text, flags=re.MULTILINE)
    text = re.sub(r"^[\s]*[-*+]\s+", "", text, flags=re.MULTILINE)
    text = re.sub(r"^[\s]*\d+\.\s+", "", text, flags=re.MULTILINE)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def md_to_html(md_text, title=None, source_file=None, date=None):
    """Markdown → 完整的交互式 HTML 页面（md2html 模板）"""
    template = _TEMPLATE_PATH.read_text(encoding="utf-8")

    # 从 markdown 提取 h1（如果调用方未提供 title）
    h1_match = re.search(r"^#\s+(.+)$", md_text, re.MULTILINE)
    if not title and h1_match:
        title = h1_match.group(1).strip()
    title = title or "文档"

    subtitle = _extract_subtitle(md_text)
    minutes = _count_reading_minutes(md_text)
    read_time = f"约 {minutes} 分钟阅读"
    source = source_file or ""
    today = date or date_type.today().isoformat()
    toc_html, body_html = _build_toc_and_body(md_text)

    # 填充模板
    html = template
    for placeholder, value in {
        "{{LANG}}": "zh",
        "{{REC_LABEL}}": "★ 推荐",
        "{{TITLE}}": title,
        "{{SUBTITLE}}": subtitle,
        "{{DOC_TYPE}}": "NOTES",
        "{{SOURCE_FILE}}": source,
        "{{DATE}}": today,
        "{{READ_TIME}}": read_time,
        "{{BRAND_LABEL}}": "笔记",
        "{{TOC_TITLE}}": "目录",
        "{{PRINT_TOOLTIP}}": "打印 / 保存 PDF",
        "{{THEME_TOOLTIP}}": "切换主题",
        "{{CLOSE_LABEL}}": "关闭",
        "{{SKIP_LINK_LABEL}}": "跳到正文",
        "{{FOOTER_NOTE}}": f"来源: {source}" if source else "Generated by Video-to-Doc",
        "<!-- TOC_ENTRIES -->": toc_html,
    }.items():
        html = html.replace(placeholder, value)

    # 注入正文 HTML（替换模板中的占位注释）
    html = html.replace(
        "<!-- Inject components here. See components.md for the catalog. -->",
        body_html,
    )

    return html


def save_formats(md_text, base_path, formats, meta=None):
    """根据选中的格式保存文件，返回保存的文件路径列表"""
    if meta is None:
        meta = {}
    saved = []
    title = meta.get("title", "")
    source_file = meta.get("source_file", base_path.name)

    for fmt in formats:
        if fmt == "md":
            path = base_path.with_suffix(".md")
            path.write_text(md_text, encoding="utf-8")
            saved.append(path)
        elif fmt == "html":
            path = base_path.with_suffix(".html")
            converted = md_to_html(md_text, title=title, source_file=source_file)
            path.write_text(converted, encoding="utf-8")
            saved.append(path)
        elif fmt == "txt":
            path = base_path.with_suffix(".txt")
            converted = md_to_txt(md_text)
            path.write_text(converted, encoding="utf-8")
            saved.append(path)
    return saved
